# We want to add dependency for starting udev service. This is usually done
# by creating configuration directory and file in
# /etc/systemd/system/<service-name>.service.d/<config-name>.conf.
#
# The file in aformentioned path will extend already existing .service file.
#
# There is also automatic way of doing this by invoking sytemctl edit <name>.service
#
# After the configuration is done, do systemctl daemon-reload.
#
# Check: https://serverfault.com/questions/840996/modify-systemd-unit-file-without-altering-upstream-unit-file
# 
# In our case, we want to override systemd-udevd.service, we'll store the .conf file in
# /etc/systemd/system/systemd-udevd.service.d/10-wait-gamepad-daemon.conf
#
# We'll doit this way (instead of invoking the sysctl command) because we want to do it
# autmatically during image creation in yocto. 

# /etc/systemd/system/systemd-udevd.service.d/10-wait-gamepad-daemon.confp

# This file will make sure that systemd-udevd.service really waits for sd_notify("READY=1") event
# from gamepad-daemon.

[Unit]
Requires=gadget.service
After=gadget.service