# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "meta-usbgadgetos"
BBFILE_PATTERN_meta-usbgadgetos = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-usbgadgetos = "6"

LAYERDEPENDS_meta-usbgadgetos = "core"
LAYERSERIES_COMPAT_meta-usbgadgetos = "whinlatter"

BBFILES_DYNAMIC += " \
		raspberrypi:${LAYERDIR}/recipes-kernel/linux/linux-raspberrypi_%.bbappend \
		riscv-layer:${LAYERDIR}/recipes-kernel/linux/linux-allwinnerd1-dev.bbappend \
"
