require conf/distro/poky.conf

DISTRO = "usbgadgetos"
DISTRO_NAME = "USB Gadget OS"
DISTRO_VERSION = "1.0"

#
# For some odd reason, yocto has default ROOT_HOME set to /home/root.
# When using systemd this results with annoying warning. So set ROOT_HOME
# to reasonable value
#
ROOT_HOME = "/root"
INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -d /root root"

INIT_MANAGER = "systemd"
DISTRO_FEATURES:append = " systemd usrmerge"
DISTRO_FEATURES_BACKFILL_CONSIDERED += " sysvinit"

VIRTUAL-RUNTIME_init_scripts = ""

PACKAGE_CLASSES ?= "package_ipkg"

# Gadget mode. This was necessary for raspberry pi, I'm not sure about Mango PI.
# Anyway, leave it here, I don't want to test my luck. It doesn't hurt anyway
ENABLE_DWC2_PERIPHERAL = "1"

# Kernel modules (commented out as we're using everything in monolyth)
# KERNEL_MODULE_AUTOLOAD += "dwc2 libcomposite usb_f_hid usb_f_ecm"
